name: Deploy Laravel 12 + Vue 3 via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy over SSH
        run: |
          ssh -p 5425 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_PATH }}

            echo "→ Pulling latest code..."
            git pull origin main

            echo "→ Installing PHP dependencies..."
            composer install --no-dev --optimize-autoloader

            echo "→ Installing JS dependencies..."
            npm ci

            echo "→ Building frontend..."
            npm run build

            echo "→ Running Laravel optimizations..."
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "→ Setting correct permissions..."
            chown -R www-data:www-data storage bootstrap/cache
            chmod -R 775 storage bootstrap/cache
          EOF
